# Generated by Django 4.2.4 on 2023-08-08 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('man', 'Hombre'), ('woman', 'Mujer'), ('boy', 'Niño'), ('girl', 'Niña'), ('girlfriend', 'Novias'), ('first_communion', 'Primera comunion'), ('quinceanera', '15 años'), ('accessories', 'Accesorios')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.IntegerField()),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('reference', models.CharField(max_length=40)),
                ('measures', models.JSONField(blank=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dress_rental.category')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rental', 'Alquiler'), ('sale', 'Venta')], max_length=30)),
                ('price', models.IntegerField()),
                ('advance_payment', models.IntegerField()),
                ('advance_payment_date', models.DateField()),
                ('outstanding_balance', models.IntegerField(blank=True)),
                ('is_product_delivered', models.BooleanField(default=False)),
                ('delivery_date', models.DateField()),
                ('return_date', models.DateField(blank=True)),
                ('is_return', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dress_rental.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dress_rental.product')),
            ],
        ),
    ]
