# Generated by Django 4.2.4 on 2023-08-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress_rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='measures',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
