# Generated by Django 4.2.4 on 2023-08-22 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dress_rental', '0002_alter_product_measures_alter_sale_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dress_rental.customer'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dress_rental.product'),
        ),
    ]
